[2025-10-07 22:44:45] ERROR rid=a6b8c87b route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:44:45] INFO 127.0.0.1 - - [07/Oct/2025 22:44:45] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 22:45:24] INFO 127.0.0.1 - - [07/Oct/2025 22:45:24] "GET /about HTTP/1.1" 200 -
[2025-10-07 22:45:24] INFO 127.0.0.1 - - [07/Oct/2025 22:45:24] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 22:45:24] INFO 127.0.0.1 - - [07/Oct/2025 22:45:24] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 22:45:24] INFO 127.0.0.1 - - [07/Oct/2025 22:45:24] "GET /static/style.css HTTP/1.1" 200 -
[2025-10-07 22:45:24] ERROR rid=32affd0f route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:45:24] INFO 127.0.0.1 - - [07/Oct/2025 22:45:24] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 22:45:25] INFO 127.0.0.1 - - [07/Oct/2025 22:45:25] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 22:45:25] INFO 127.0.0.1 - - [07/Oct/2025 22:45:25] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 22:45:25] INFO 127.0.0.1 - - [07/Oct/2025 22:45:25] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 22:45:25] ERROR rid=93df7696 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:45:25] INFO 127.0.0.1 - - [07/Oct/2025 22:45:25] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 22:45:34] INFO 127.0.0.1 - - [07/Oct/2025 22:45:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 22:45:34] ERROR rid=aaa004f1 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:45:34] INFO 127.0.0.1 - - [07/Oct/2025 22:45:34] "[35m[1mGET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1[0m" 500 -
[2025-10-07 22:47:50] INFO 127.0.0.1 - - [07/Oct/2025 22:47:50] "GET /about HTTP/1.1" 200 -
[2025-10-07 22:47:50] INFO 127.0.0.1 - - [07/Oct/2025 22:47:50] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 22:47:50] INFO 127.0.0.1 - - [07/Oct/2025 22:47:50] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 22:47:50] INFO 127.0.0.1 - - [07/Oct/2025 22:47:50] "GET /static/style.css HTTP/1.1" 200 -
[2025-10-07 22:47:50] ERROR rid=04e792ae route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:47:50] INFO 127.0.0.1 - - [07/Oct/2025 22:47:50] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 22:47:51] INFO 127.0.0.1 - - [07/Oct/2025 22:47:51] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 22:47:51] INFO 127.0.0.1 - - [07/Oct/2025 22:47:51] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 22:47:51] INFO 127.0.0.1 - - [07/Oct/2025 22:47:51] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 22:47:51] ERROR rid=0b891a39 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:47:51] INFO 127.0.0.1 - - [07/Oct/2025 22:47:51] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 22:50:30] INFO 127.0.0.1 - - [07/Oct/2025 22:50:30] "GET /about HTTP/1.1" 200 -
[2025-10-07 22:50:30] INFO 127.0.0.1 - - [07/Oct/2025 22:50:30] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 22:50:30] INFO 127.0.0.1 - - [07/Oct/2025 22:50:30] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 22:50:30] INFO 127.0.0.1 - - [07/Oct/2025 22:50:30] "GET /static/style.css HTTP/1.1" 200 -
[2025-10-07 22:50:30] ERROR rid=f5e6c8d4 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:50:30] INFO 127.0.0.1 - - [07/Oct/2025 22:50:30] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 22:50:31] INFO 127.0.0.1 - - [07/Oct/2025 22:50:31] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 22:50:31] INFO 127.0.0.1 - - [07/Oct/2025 22:50:31] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 22:50:31] INFO 127.0.0.1 - - [07/Oct/2025 22:50:31] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 22:50:31] ERROR rid=8921afd6 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 22:50:31] INFO 127.0.0.1 - - [07/Oct/2025 22:50:31] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:03:57] INFO 127.0.0.1 - - [07/Oct/2025 23:03:57] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:03:57] INFO 127.0.0.1 - - [07/Oct/2025 23:03:57] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:03:57] INFO 127.0.0.1 - - [07/Oct/2025 23:03:57] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:03:57] INFO 127.0.0.1 - - [07/Oct/2025 23:03:57] "GET /static/style.css HTTP/1.1" 200 -
[2025-10-07 23:03:57] ERROR rid=1acce6d8 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:03:57] INFO 127.0.0.1 - - [07/Oct/2025 23:03:57] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:03:58] INFO 127.0.0.1 - - [07/Oct/2025 23:03:58] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 23:03:58] INFO 127.0.0.1 - - [07/Oct/2025 23:03:58] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:03:58] INFO 127.0.0.1 - - [07/Oct/2025 23:03:58] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:03:58] ERROR rid=8b001d4c route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:03:58] INFO 127.0.0.1 - - [07/Oct/2025 23:03:58] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:26] INFO 127.0.0.1 - - [07/Oct/2025 23:04:26] "GET /contact HTTP/1.1" 200 -
[2025-10-07 23:04:26] INFO 127.0.0.1 - - [07/Oct/2025 23:04:26] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:04:26] INFO 127.0.0.1 - - [07/Oct/2025 23:04:26] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:27] ERROR rid=99a423ba route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:27] INFO 127.0.0.1 - - [07/Oct/2025 23:04:27] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:30] INFO 127.0.0.1 - - [07/Oct/2025 23:04:30] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 23:04:30] INFO 127.0.0.1 - - [07/Oct/2025 23:04:30] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:04:30] INFO 127.0.0.1 - - [07/Oct/2025 23:04:30] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:30] ERROR rid=71e49db7 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:30] INFO 127.0.0.1 - - [07/Oct/2025 23:04:30] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:32] INFO 127.0.0.1 - - [07/Oct/2025 23:04:32] "GET /contact HTTP/1.1" 200 -
[2025-10-07 23:04:32] INFO 127.0.0.1 - - [07/Oct/2025 23:04:32] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:04:32] INFO 127.0.0.1 - - [07/Oct/2025 23:04:32] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:32] ERROR rid=9c7c5e56 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:32] INFO 127.0.0.1 - - [07/Oct/2025 23:04:32] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:34] INFO 127.0.0.1 - - [07/Oct/2025 23:04:34] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 23:04:34] INFO 127.0.0.1 - - [07/Oct/2025 23:04:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:04:34] INFO 127.0.0.1 - - [07/Oct/2025 23:04:34] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:34] ERROR rid=f4a44ca4 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:34] INFO 127.0.0.1 - - [07/Oct/2025 23:04:34] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:36] INFO 127.0.0.1 - - [07/Oct/2025 23:04:36] "GET /contact HTTP/1.1" 200 -
[2025-10-07 23:04:36] INFO 127.0.0.1 - - [07/Oct/2025 23:04:36] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:04:36] INFO 127.0.0.1 - - [07/Oct/2025 23:04:36] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:36] ERROR rid=e090da41 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:36] INFO 127.0.0.1 - - [07/Oct/2025 23:04:36] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:39] INFO 127.0.0.1 - - [07/Oct/2025 23:04:39] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:04:39] INFO 127.0.0.1 - - [07/Oct/2025 23:04:39] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:39] INFO 127.0.0.1 - - [07/Oct/2025 23:04:39] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:04:39] INFO 127.0.0.1 - - [07/Oct/2025 23:04:39] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:04:39] ERROR rid=a8485924 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:39] INFO 127.0.0.1 - - [07/Oct/2025 23:04:39] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:04:45] INFO 127.0.0.1 - - [07/Oct/2025 23:04:45] "GET / HTTP/1.1" 200 -
[2025-10-07 23:04:45] INFO 127.0.0.1 - - [07/Oct/2025 23:04:45] "GET /static/style.css?v=3 HTTP/1.1" 200 -
[2025-10-07 23:04:45] INFO 127.0.0.1 - - [07/Oct/2025 23:04:45] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:04:45] ERROR rid=c32f9cfc route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:04:45] INFO 127.0.0.1 - - [07/Oct/2025 23:04:45] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:08:00] INFO 127.0.0.1 - - [07/Oct/2025 23:08:00] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:08:00] INFO 127.0.0.1 - - [07/Oct/2025 23:08:00] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:08:00] INFO 127.0.0.1 - - [07/Oct/2025 23:08:00] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:08:00] INFO 127.0.0.1 - - [07/Oct/2025 23:08:00] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:08:01] ERROR rid=bab7e147 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:08:01] INFO 127.0.0.1 - - [07/Oct/2025 23:08:01] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:08:12] INFO 127.0.0.1 - - [07/Oct/2025 23:08:12] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 23:08:12] INFO 127.0.0.1 - - [07/Oct/2025 23:08:12] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:08:12] INFO 127.0.0.1 - - [07/Oct/2025 23:08:12] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:08:12] ERROR rid=11d17ced route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:08:12] INFO 127.0.0.1 - - [07/Oct/2025 23:08:12] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:08:27] INFO 127.0.0.1 - - [07/Oct/2025 23:08:27] "GET /contact HTTP/1.1" 200 -
[2025-10-07 23:08:27] INFO 127.0.0.1 - - [07/Oct/2025 23:08:27] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:08:27] INFO 127.0.0.1 - - [07/Oct/2025 23:08:27] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:08:28] ERROR rid=8c2f43ef route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:08:28] INFO 127.0.0.1 - - [07/Oct/2025 23:08:28] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:08:42] INFO 127.0.0.1 - - [07/Oct/2025 23:08:42] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:08:42] INFO 127.0.0.1 - - [07/Oct/2025 23:08:42] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:08:42] INFO 127.0.0.1 - - [07/Oct/2025 23:08:42] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:08:42] INFO 127.0.0.1 - - [07/Oct/2025 23:08:42] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:08:42] ERROR rid=5bafd5c4 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:08:42] INFO 127.0.0.1 - - [07/Oct/2025 23:08:42] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:09:02] INFO 127.0.0.1 - - [07/Oct/2025 23:09:02] "GET /contact HTTP/1.1" 200 -
[2025-10-07 23:09:02] INFO 127.0.0.1 - - [07/Oct/2025 23:09:02] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:09:02] INFO 127.0.0.1 - - [07/Oct/2025 23:09:02] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:09:02] ERROR rid=54ed16f1 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:09:02] INFO 127.0.0.1 - - [07/Oct/2025 23:09:02] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:09:29] INFO 127.0.0.1 - - [07/Oct/2025 23:09:29] "GET / HTTP/1.1" 200 -
[2025-10-07 23:09:29] INFO 127.0.0.1 - - [07/Oct/2025 23:09:29] "[36mGET /static/style.css?v=3 HTTP/1.1[0m" 304 -
[2025-10-07 23:09:29] INFO 127.0.0.1 - - [07/Oct/2025 23:09:29] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:09:29] ERROR rid=152d379b route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:09:29] INFO 127.0.0.1 - - [07/Oct/2025 23:09:29] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:10:34] INFO 127.0.0.1 - - [07/Oct/2025 23:10:34] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:10:34] INFO 127.0.0.1 - - [07/Oct/2025 23:10:34] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:10:34] INFO 127.0.0.1 - - [07/Oct/2025 23:10:34] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:10:34] INFO 127.0.0.1 - - [07/Oct/2025 23:10:34] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:10:34] ERROR rid=edc057fc route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:10:34] INFO 127.0.0.1 - - [07/Oct/2025 23:10:34] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:10:35] INFO 127.0.0.1 - - [07/Oct/2025 23:10:35] "GET / HTTP/1.1" 200 -
[2025-10-07 23:10:35] INFO 127.0.0.1 - - [07/Oct/2025 23:10:35] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:10:35] INFO 127.0.0.1 - - [07/Oct/2025 23:10:35] "[36mGET /static/style.css?v=3 HTTP/1.1[0m" 304 -
[2025-10-07 23:10:36] ERROR rid=d5b180ce route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:10:36] INFO 127.0.0.1 - - [07/Oct/2025 23:10:36] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:10:56] INFO 127.0.0.1 - - [07/Oct/2025 23:10:56] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:10:56] INFO 127.0.0.1 - - [07/Oct/2025 23:10:56] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:10:56] INFO 127.0.0.1 - - [07/Oct/2025 23:10:56] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:10:56] INFO 127.0.0.1 - - [07/Oct/2025 23:10:56] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:10:56] ERROR rid=7f30c020 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:10:56] INFO 127.0.0.1 - - [07/Oct/2025 23:10:56] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:11:15] INFO 127.0.0.1 - - [07/Oct/2025 23:11:15] "GET /how-it-works HTTP/1.1" 200 -
[2025-10-07 23:11:15] INFO 127.0.0.1 - - [07/Oct/2025 23:11:15] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:11:15] INFO 127.0.0.1 - - [07/Oct/2025 23:11:15] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:11:15] ERROR rid=c77e4773 route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:11:15] INFO 127.0.0.1 - - [07/Oct/2025 23:11:15] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
[2025-10-07 23:11:16] INFO 127.0.0.1 - - [07/Oct/2025 23:11:16] "GET /about HTTP/1.1" 200 -
[2025-10-07 23:11:17] INFO 127.0.0.1 - - [07/Oct/2025 23:11:17] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
[2025-10-07 23:11:17] INFO 127.0.0.1 - - [07/Oct/2025 23:11:17] "[36mGET /static/logo.svg HTTP/1.1[0m" 304 -
[2025-10-07 23:11:17] INFO 127.0.0.1 - - [07/Oct/2025 23:11:17] "[36mGET /static/me2.png HTTP/1.1[0m" 304 -
[2025-10-07 23:11:17] ERROR rid=bc537c3f route=unhandled 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 891, in dispatch_request
    self.raise_routing_exception(req)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 500, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "C:\Users\91932\AppData\Local\Programs\Python\Python313\Lib\site-packages\werkzeug\routing\map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
[2025-10-07 23:11:17] INFO 127.0.0.1 - - [07/Oct/2025 23:11:17] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
